version: '3.6'

services:
  apache:
    image: httpd
    container_name: apache
    restart: always
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:8060:8060'
      - '0.0.0.0:8070:8070'
    volumes:
      - ./http-files:/usr/local/apache2/htdocs:ro
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./logs:/usr/local/apache2/logs:rw
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - '127.0.0.1:8086:8086'
    volumes:
      - ./dbdata:/var/lib/influxdb2/engine/data:rw
  influxdb_cli:
    links:
      - influxdb
    image: influxdb

    entrypoint: influx setup --bucket ${influx_bucket:-apache_bucket} -t ${influx_token:-apache_token} -o ${influx_org:-apache_org} --username=${influx_username:-apache_admin} --password=${influx_password:-apache_password} --host=http://influxdb:8086 -f

    restart: on-failure:20
    depends_on:
      - influxdb
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    user: telegraf:1000
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./logs:/var/log/apache2:ro
      - ./tglog:/usr/local/etc:rw
    environment:
      - INFLUXDB_ORG=${influx_org:-apache_org}
      - INFLUXDB_BUCKET=${influx_bucket:-apache_bucket}
      - INFLUXDB_TOKEN=${influx_token:-apache_token}
      - INFLUXDB_ENTRYPOINT=http://influxdb:8086
    depends_on:
      - apache
      - influxdb
    links:
      - influxdb
    ports:
      - '127.0.0.1:8125:8125'
  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources:rw
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards:rw
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${grafana_username:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${grafana_password:-admin123}
      - GF_SERVER_HTTP_PORT=3000
      - GF_INSTALL_PLUGINS=gapit-htmlgraphics-panel
      - INFLUXDB_ORG=${influx_org:-apache_org}
      - INFLUXDB_BUCKET=${influx_bucket:-apache_bucket}
      - INFLUXDB_TOKEN=${influx_token:-apache_token}
    links:
      - influxdb
    ports:
      - '0.0.0.0:3000:3000'
