version: '3.6'

services:
  apache:
    image: httpd
    container_name: apache
    restart: always
    ports:
      - '0.0.0.0:80:80'
    volumes:
      - ./apacher/build:/usr/local/apache2/htdocs:ro
