[tool.black]
# format files with selected rules
select = [
    "A", # builtins
    "B", # bugbear
    "C", # McCabe
    "E", # pycodestyle Errors
    "F", # Pyflakes
    "W"  # pycodestyle Warnings
    ]
line-length = 120
# better long string formatting
preview = true
 
[tool.ruff]
# https://beta.ruff.rs/docs/rules/
# check lintings
select = [
    "A", # builtins
    "B", # bugbear
    "C", # McCabe
    "E", # pycodestyle Errors
    "F", # Pyflakes
    "W", # pycodestyle Warnings
    "I", # isort
    "N", # naming
    "Q"  # quotes
    ]
# try to autofix linting problems
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
ignore = [
    "B905", # zip() without an explicit strict= parameter set. Python >= 3.10
    "B006", # Do not use mutable data structures for argument defaults
    "B008", # Do not perform function calls in argument defaults
    "N803", # argument name should be lowercase
    "N812", # lowercase imported as non-lowercase
    "N806", # variable in function should be lowercase
 
    # Ignored temporary:
    "C901", # Function is too complex
    "F811" # Redefinition of unused name
    ]
line-length = 120
target-version = "py39"