{
 "title": "Apache log stats",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Port",
    "label": "Port",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"port\",\n    predicate: (r) => true,\n    start: -1d\n)"
   },
   {
    "name": "access_file",
    "label": "Access file",
    "query": "from(bucket: \"apache_bucket\")\n|> range(start: -24h)\n|> filter(fn: (r) => r[\"_measurement\"] == \"access\" and r[\"_field\"] == \"resp_time\")\n|> group(columns: [\"path\"])\n|> distinct(column: \"path\")\n|> keep(columns: [\"_value\"])"
   },
   {
    "name": "error_file",
    "label": "Error file",
    "query": "from(bucket: \"apache_bucket\")\n|> range(start: -24h)\n|> filter(fn: (r) => r[\"_measurement\"] == \"error\" and r[\"_field\"] == \"message\")\n|> group(columns: [\"path\"])\n|> distinct(column: \"path\")\n|> keep(columns: [\"_value\"])"
   },
   {
    "name": "error_loglevel",
    "label": "Error level",
    "query": "from(bucket: \"apache_bucket\")\n|> range(start: -24h)\n|> filter(fn: (r) => r[\"_measurement\"] == \"error\" and r[\"_field\"] == \"message\")\n|> group(columns: [\"level\"])\n|> distinct(column: \"level\")\n|> keep(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  { "title": "Access", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response time [port: $Port | log: $access_file]",
   "type": "barchart",
   "description": "Response time in the last 24 hours.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "keeps = if \"${Port}\" == \"All\" then [\"_time\", \"_value\", \"port\"] else [\"_time\", \"_value\"]\n\nfrom(bucket: \"apache_bucket\")\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n|> filter(\n  fn: (r) => if \"${Port}\" == \"All\" then \n    r[\"_measurement\"] == \"access\" and r[\"_field\"] == \"resp_time\" and (r[\"path\"] == \"${access_file}\" or \"${access_file}\" == \"All\")\n  else\n    r[\"_measurement\"] == \"access\" and r[\"_field\"] == \"resp_time\" and r[\"port\"] == \"${Port}\" and (r[\"path\"] == \"${access_file}\" or \"${access_file}\" == \"All\")\n  )\n  |> keep(columns: keeps)\n  |> sort(columns: [\"_time\"])\n"
    }
   ]
  },
  {
   "title": "Response code [port: $Port | log: $access_file]",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"apache_bucket\")\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"access\" and r[\"_field\"] == \"resp_time\" and (r[\"path\"] == \"${access_file}\" or \"${access_file}\" == \"All\") and (r[\"port\"] == \"${Port}\" or \"${Port}\" == \"All\"))\n|> group(columns: [\"resp_code\"], mode: \"by\")\n|> count()\n|> keep(columns: [\"resp_code\", \"_value\"])\n|> rename(columns: {_value: \"\"})"
    }
   ]
  },
  {
   "title": "HTTP Version [port: $Port | log: $access_file]",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"apache_bucket\")\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"access\" and r[\"_field\"] == \"resp_time\" and (r[\"path\"] == \"${access_file}\" or \"${access_file}\" == \"All\") and (r[\"port\"] == \"${Port}\" or \"${Port}\" == \"All\"))\n|> group(columns: [\"http_version\"], mode: \"by\")\n|> count()\n|> keep(columns: [\"http_version\", \"_value\"])\n|> rename(columns: {_value: \"HTTP \"})"
    }
   ]
  },
  {
   "title": "HTTP Method [port: $Port | log: $access_file]",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"apache_bucket\")\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"access\" and r[\"_field\"] == \"resp_time\" and (r[\"path\"] == \"${access_file}\" or \"${access_file}\" == \"All\") and (r[\"port\"] == \"${Port}\" or \"${Port}\" == \"All\"))\n|> group(columns: [\"verb\"], mode: \"by\")\n|> count()\n|> keep(columns: [\"verb\", \"_value\"])\n|> rename(columns: {_value: \"\"})"
    }
   ]
  },
  {
   "title": "Access logs [log: $access_file]",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "import \"join\"\n\nleft = from(bucket: \"apache_bucket\")\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"access\" and r[\"_field\"] == \"resp_time\" and (r[\"path\"] == \"${access_file}\" or \"${access_file}\" == \"All\"))\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> keep(columns: [\"_time\", \"resp_time\"])\n|> group(columns: [\"_time\"])\n\nright = from(bucket: \"apache_bucket\")\n|> range(start: -24h)\n|> filter(fn: (r) => r[\"_measurement\"] == \"access\" and r[\"_field\"] == \"agent\" and (r[\"path\"] == \"${access_file}\" or \"${access_file}\" == \"All\"))\n|> group(columns: [\"_time\"])\n\njoin.right(\n    left: left,\n    right: right,\n    on: (l, r) => l._time == r._time,\n    as: (l, r) => ({r with resp_time: l.resp_time}),\n)\n|> group()\n|> drop(columns: [\"_field\", \"_measurement\", \"_start\", \"_stop\"])"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Error logs [Log level: $error_loglevel | log: $error_file]",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"apache_bucket\")\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"error\" \n  and (r[\"path\"] == \"${error_file}\" or \"${error_file}\" == \"All\")\n  and (r[\"level\"] == \"${error_loglevel}\" or \"${error_loglevel}\" == \"All\")\n)"
    }
   ]
  }
 ]
}