version: '3.6'
services:
# APACHE
  apache:
    image: httpd
    container_name: apache
    restart: always
    ports:
      - 8080:80
      - 8081:8060
    volumes:
      # - ./hosts_file:/etc/hosts:ro
      - ./http-files:/usr/local/apache2/htdocs:ro
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      #- ./000-default.conf:/usr/local/apache2/sites-available/000-default.conf:ro
      - ./tetris1:/usr/local/apache2/htdocs_v2:ro
      - ./logs:/usr/local/apache2/logs:rw
  
# INFLUXDB
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    #environment:
      #- INFLUXDB_DB=influx
      #- INFLUXDB_ADMIN_USER=admin
      #- INFLUXDB_ADMIN_PASSWORD=admin123
      #- INFLUXDB_HTTP_AUTH_ENABLED
    ports:
      - '8086:8086'
        #volumes:
      #- influxdb_data:/var/lib/influxdb
  
  influxdb_cli:
    links:
      - influxdb
    image: influxdb
    container_name: influxdb_cli
    entrypoint: influx setup --bucket test_bucket -t test_token -o test_org --username=test_username --password=test_password --host=http://influxdb:8086 -f
    restart: on-failure:20
    depends_on:
      - influxdb

# TELEGRAF
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    user: telegraf:1000
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./logs:/var/log/apache2:ro
      - ./tglog:/usr/local/etc:rw
    depends_on:
      - apache
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'

# GRAFANA
  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_SERVER_HTTP_PORT=3000
      - INFLUXDB_ORG=test_org
      - INFLUXDB_BUCKET=test_bucket
      - INFLUXDB_TOKEN=test_token
    links:
      - influxdb
    ports:
      - '3000:3000'
        #volumes:
      #      - grafana_data:/var/lib/grafana
      
#volumes:
#grafana_data: {}
#influxdb_data: {}

